version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "5000:5000"
    command: python -m app
    depends_on:
      - cors

  cors:
    build:
      context: .
      dockerfile: Dockerfile.cors
    ports:
      - "8080:8080"
    command: node config/cors-anywhere.js
