FROM node:22-alpine

WORKDIR /usr/src/app

# Copy the CORS Anywhere configuration
COPY . .

# Install necessary dependencies
RUN npm install

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Run CORS Anywhere server
CMD ["node", "config/cors-anywhere.js"]
